/**
 * @file tpl_app_config.c
 *
 * @section desc File description
 *
 * OS data structure generated from application timer
 * Automatically generated by goil on Www Mmm dd hh:mm:ss yyyy
 * from root OIL file LearnInDepth_SW.oil
 *
 * @section copyright Copyright
 *
 * Trampoline OS
 *
 * Trampoline is copyright (c) IRCCyN 2005-2007
 * Trampoline is protected by the French intellectual property law.
 *
 * This software is distributed under the Lesser GNU Public Licence
 *
 * @section infos File informations
 *
 * $Date$
 * $Rev$
 * $Author$
 * $URL$
 */

#include <stdbool.h>
#include <stdint.h>

#include "tpl_app_config.h"

#include "tpl_os_internal_types.h"
#include "tpl_machine.h"
#include "tpl_os_interrupt.h"
#include "tpl_os_interrupt_kernel.h"
#include "tpl_os_alarm_kernel.h"
#include "tpl_os_alarm.h"
#include "tpl_os_resource_kernel.h"
#include "tpl_os_resource.h"
#include "tpl_os_event_kernel.h"
#include "tpl_os_event.h"
#include "tpl_os_action.h"
#include "tpl_os_kernel.h"
#include "tpl_os_definitions.h"


/*=============================================================================
 * Application Modes tables for tasks, alarms and schedule tables
 * Application Modes masks are as follow:
 * AppStd = 1
 */

CONST(tpl_application_mode, OS_CONST) AppStd = 0; /* mask = 1 */
CONST(tpl_application_mode, OS_CONST) OSDEFAULTAPPMODE = 0;
CONST(tpl_appmode_mask, OS_CONST) tpl_task_app_mode[TASK_COUNT] = {
  1 /* task DoorLockIndicationTask : AppStd */ ,
  1 /* task LEDSwitchTask : AppStd */ ,
  1 /* task ReadDoorT : AppStd */ 
};

CONST(tpl_appmode_mask, OS_CONST) tpl_alarm_app_mode[ALARM_COUNT] = {
  1 /* alarm Time10ms_Alarm : AppStd */ 
};

#define API_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

/*=============================================================================
 * Declaration of event masks
 */

/* Event LedSwitchInvokeEvent */
#define LedSwitchInvokeEvent_mask 1
CONST(EventMaskType, AUTOMATIC) LedSwitchInvokeEvent = LedSwitchInvokeEvent_mask;

/* Event Time_10ms_Event */
#define Time_10ms_Event_mask 1
CONST(EventMaskType, AUTOMATIC) Time_10ms_Event = Time_10ms_Event_mask;

/* Event DoorStateReceivedEvent */
#define DoorStateReceivedEvent_mask 1
CONST(EventMaskType, AUTOMATIC) DoorStateReceivedEvent = DoorStateReceivedEvent_mask;

/*=============================================================================
 * Declaration of processes IDs
 */

/* Task DoorLockIndicationTask identifier */
#define DoorLockIndicationTask_id 0
CONST(TaskType, AUTOMATIC) DoorLockIndicationTask = DoorLockIndicationTask_id;

/* Task LEDSwitchTask identifier */
#define LEDSwitchTask_id 1
CONST(TaskType, AUTOMATIC) LEDSwitchTask = LEDSwitchTask_id;

/* Task ReadDoorT identifier */
#define ReadDoorT_id 2
CONST(TaskType, AUTOMATIC) ReadDoorT = ReadDoorT_id;

/*=============================================================================
 * Declaration of Alarm IDs
 */

/* Alarm Time10ms_Alarm identifier */
#define Time10ms_Alarm_id 0
CONST(AlarmType, AUTOMATIC) Time10ms_Alarm = Time10ms_Alarm_id;

#define API_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

/**
 * The scheduler resource descriptor.
 * One scheduler resource is defined per core.
 *
 * @see #RES_SCHEDULER
 */

#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
VAR(tpl_resource, OS_VAR) res_sched_rez_desc = {
  RES_SCHEDULER_PRIORITY,   /*  ceiling priority                            */
  0,                        /*  owner_prev_priority                         */
  INVALID_PROC_ID,          /*  owner                                       */
#if WITH_OSAPPLICATION == YES
  INVALID_OSAPPLICATION_ID, /*  OS Application id                           */
#endif

  NULL                      /*  next_res                                    */
};
#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"
CONSTP2VAR(tpl_resource, AUTOMATIC, OS_APPL_DATA)
tpl_resource_table[RESOURCE_COUNT] = {
  &res_sched_rez_desc
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

/*=============================================================================
 * Definition and initialization of Counters related defines and structures
 */
/*-----------------------------------------------------------------------------
 * Counter SystemCounter descriptor
 */

#define API_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

CONST(tpl_tick, OS_CONST) OSTICKSPERBASE = 1;
CONST(tpl_tick, OS_CONST) OSMAXALLOWEDVALUE = 65535;
CONST(tpl_tick, OS_CONST) OSMINCYCLE = 1;

#define API_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

VAR(tpl_counter, OS_VAR) SystemCounter_counter_desc = {
  /* ticks per base       */  1,
  /* max allowed value    */  65535,
  /* minimum cycle        */  1,
  /* current tick         */  0,
  /* current date         */  0,
#if WITH_OSAPPLICATION == YES
    /* OS Application id    */  
#endif
    /* first alarm          */  NULL_PTR,
    /* next alarm to raise  */  NULL_PTR
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#include "tpl_os_kernel.h"          /* tpl_schedule */
#include "tpl_os_timeobj_kernel.h"  /* tpl_counter_tick */
#include "tpl_machine_interface.h"  /* tpl_switch_context_from_it */

#define OS_START_SEC_VAR_32BIT
#include "tpl_memmap.h"
volatile VAR(uint32, OS_VAR) tpl_time_counter = 0;
#define OS_STOP_SEC_VAR_32BIT
#include "tpl_memmap.h"

#define OS_START_SEC_CODE
#include "tpl_memmap.h"

FUNC(tpl_bool, OS_CODE) tpl_tick_SysTick(void)
{
  tpl_counter_tick(&SystemCounter_counter_desc);
  tpl_time_counter++;

  if (tpl_kern.need_schedule == TRUE)
  {
    tpl_schedule_from_running();
    LOCAL_SWITCH_CONTEXT()
  }

  return TRUE;
}

#define OS_STOP_SEC_CODE
#include "tpl_memmap.h"

/*=============================================================================
 * Descriptor(s) of the idle task(s)
 */
/*-----------------------------------------------------------------------------
 * Task IDLE_TASK descriptor
 */
#define OS_START_SEC_CODE
#include "tpl_memmap.h"
/*
 * Task IDLE_TASK function prototype
 */

FUNC(void, OS_APPL_CODE) idle_function(void);
#define OS_STOP_SEC_CODE
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Target specific structures
 */
/*
 * Task IDLE_TASK stack
 */
#define APP_Task_IDLE_TASK_START_SEC_STACK
#include "tpl_memmap.h"
VAR(tpl_stack_word, OS_APPL_DATA) IDLE_TASK_stack_zone[IDLE_STACK_SIZE/sizeof(tpl_stack_word)];
#define APP_Task_IDLE_TASK_STOP_SEC_STACK
#include "tpl_memmap.h"

#define IDLE_TASK_STACK {IDLE_TASK_stack_zone, IDLE_STACK_SIZE}

/*
 * Task IDLE_TASK context
 */
#define OS_START_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"
VAR(arm_core_context, OS_VAR) IDLE_TASK_int_context;

#define IDLE_TASK_CONTEXT &IDLE_TASK_int_context

#define OS_STOP_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"




/*
  No timing protection
 */

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*
 * Static descriptor of task IDLE_TASK
 */
CONST(tpl_proc_static, OS_CONST) IDLE_TASK_task_stat_desc = {
  /* context                  */  IDLE_TASK_CONTEXT,
  /* stack                    */  IDLE_TASK_STACK,
  /* entry point (function)   */  idle_function,
  /* internal ressource       */  NULL,
  /* task id                  */  IDLE_TASK_ID,
#if WITH_OSAPPLICATION == YES
  /* OS application id        */  
#endif
  /* task base priority       */  0,
  /* max activation count     */  1,
  /* task type                */  TASK_BASIC,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES

  /* execution budget */        0,
  /* timeframe        */        0, 
  /* pointer to the timing
     protection descriptor    */ NULL

#endif
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
/*
 * Dynamic descriptor of task IDLE_TASK
 */
VAR(tpl_proc, OS_VAR) IDLE_TASK_task_desc = {
  /* resources                      */  NULL,
#if WITH_OSAPPLICATION == YES
  /* if > 0 the process is trusted  */  0,    
#endif /* WITH_OSAPPLICATION */
  /* activate count                 */  0,
  /* task priority                  */  0,
  /* task state                     */  SUSPENDED
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"


/*=============================================================================
 * Definition and initialization of Task related defines and structures
 */
/*-----------------------------------------------------------------------------
 * Task DoorLockIndicationTask descriptor
 */
#define APP_Task_DoorLockIndicationTask_START_SEC_CODE

#include "tpl_memmap.h"
/*
 * Task DoorLockIndicationTask function prototype
 */

FUNC(void, OS_APPL_CODE) DoorLockIndicationTask_function(void);
#define APP_Task_DoorLockIndicationTask_STOP_SEC_CODE

#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Target specific structures
 */
/*
 * Task DoorLockIndicationTask stack
 */
#define APP_Task_DoorLockIndicationTask_START_SEC_STACK
#include "tpl_memmap.h"
VAR(tpl_stack_word, OS_APPL_DATA) DoorLockIndicationTask_stack_zone[3000/sizeof(tpl_stack_word)];
#define APP_Task_DoorLockIndicationTask_STOP_SEC_STACK
#include "tpl_memmap.h"

#define DoorLockIndicationTask_STACK {DoorLockIndicationTask_stack_zone, 3000}

/*
 * Task DoorLockIndicationTask context
 */
#define OS_START_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"
VAR(arm_core_context, OS_VAR) DoorLockIndicationTask_int_context;

#define DoorLockIndicationTask_CONTEXT &DoorLockIndicationTask_int_context

#define OS_STOP_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"




/*
  No timing protection
 */

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*
 * Static descriptor of task DoorLockIndicationTask
 */
CONST(tpl_proc_static, OS_CONST) DoorLockIndicationTask_task_stat_desc = {
  /* context                  */  DoorLockIndicationTask_CONTEXT,
  /* stack                    */  DoorLockIndicationTask_STACK,
  /* entry point (function)   */  DoorLockIndicationTask_function,
  /* internal ressource       */  NULL,
  /* task id                  */  DoorLockIndicationTask_id,
#if WITH_OSAPPLICATION == YES
  /* OS application id        */  
#endif
  /* task base priority       */  1,
  /* max activation count     */  1,
  /* task type                */  TASK_EXTENDED,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES

  /* execution budget */        0,
  /* timeframe        */        0, 
  /* pointer to the timing
     protection descriptor    */ NULL

#endif
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
/*
 * Dynamic descriptor of task DoorLockIndicationTask
 */
VAR(tpl_proc, OS_VAR) DoorLockIndicationTask_task_desc = {
  /* resources                      */  NULL,
#if WITH_OSAPPLICATION == YES
  /* if > 0 the process is trusted  */  0,    
#endif /* WITH_OSAPPLICATION */
  /* activate count                 */  0,
  /* task priority                  */  1,
  /* task state                     */  AUTOSTART
};

/*
 * Event structure of task DoorLockIndicationTask
 */
VAR(tpl_task_events, OS_VAR) DoorLockIndicationTask_task_evts = {
  /* event set  */ 0,
  /* event wait */ 0
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Task LEDSwitchTask descriptor
 */
#define APP_Task_LEDSwitchTask_START_SEC_CODE

#include "tpl_memmap.h"
/*
 * Task LEDSwitchTask function prototype
 */

FUNC(void, OS_APPL_CODE) LEDSwitchTask_function(void);
#define APP_Task_LEDSwitchTask_STOP_SEC_CODE

#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Target specific structures
 */
/*
 * Task LEDSwitchTask stack
 */
#define APP_Task_LEDSwitchTask_START_SEC_STACK
#include "tpl_memmap.h"
VAR(tpl_stack_word, OS_APPL_DATA) LEDSwitchTask_stack_zone[3000/sizeof(tpl_stack_word)];
#define APP_Task_LEDSwitchTask_STOP_SEC_STACK
#include "tpl_memmap.h"

#define LEDSwitchTask_STACK {LEDSwitchTask_stack_zone, 3000}

/*
 * Task LEDSwitchTask context
 */
#define OS_START_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"
VAR(arm_core_context, OS_VAR) LEDSwitchTask_int_context;

#define LEDSwitchTask_CONTEXT &LEDSwitchTask_int_context

#define OS_STOP_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"




/*
  No timing protection
 */

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*
 * Static descriptor of task LEDSwitchTask
 */
CONST(tpl_proc_static, OS_CONST) LEDSwitchTask_task_stat_desc = {
  /* context                  */  LEDSwitchTask_CONTEXT,
  /* stack                    */  LEDSwitchTask_STACK,
  /* entry point (function)   */  LEDSwitchTask_function,
  /* internal ressource       */  NULL,
  /* task id                  */  LEDSwitchTask_id,
#if WITH_OSAPPLICATION == YES
  /* OS application id        */  
#endif
  /* task base priority       */  2,
  /* max activation count     */  1,
  /* task type                */  TASK_EXTENDED,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES

  /* execution budget */        0,
  /* timeframe        */        0, 
  /* pointer to the timing
     protection descriptor    */ NULL

#endif
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
/*
 * Dynamic descriptor of task LEDSwitchTask
 */
VAR(tpl_proc, OS_VAR) LEDSwitchTask_task_desc = {
  /* resources                      */  NULL,
#if WITH_OSAPPLICATION == YES
  /* if > 0 the process is trusted  */  0,    
#endif /* WITH_OSAPPLICATION */
  /* activate count                 */  0,
  /* task priority                  */  2,
  /* task state                     */  AUTOSTART
};

/*
 * Event structure of task LEDSwitchTask
 */
VAR(tpl_task_events, OS_VAR) LEDSwitchTask_task_evts = {
  /* event set  */ 0,
  /* event wait */ 0
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Task ReadDoorT descriptor
 */
#define APP_Task_ReadDoorT_START_SEC_CODE

#include "tpl_memmap.h"
/*
 * Task ReadDoorT function prototype
 */

FUNC(void, OS_APPL_CODE) ReadDoorT_function(void);
#define APP_Task_ReadDoorT_STOP_SEC_CODE

#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Target specific structures
 */
/*
 * Task ReadDoorT stack
 */
#define APP_Task_ReadDoorT_START_SEC_STACK
#include "tpl_memmap.h"
VAR(tpl_stack_word, OS_APPL_DATA) ReadDoorT_stack_zone[3000/sizeof(tpl_stack_word)];
#define APP_Task_ReadDoorT_STOP_SEC_STACK
#include "tpl_memmap.h"

#define ReadDoorT_STACK {ReadDoorT_stack_zone, 3000}

/*
 * Task ReadDoorT context
 */
#define OS_START_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"
VAR(arm_core_context, OS_VAR) ReadDoorT_int_context;

#define ReadDoorT_CONTEXT &ReadDoorT_int_context

#define OS_STOP_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"




/*
  No timing protection
 */

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*
 * Static descriptor of task ReadDoorT
 */
CONST(tpl_proc_static, OS_CONST) ReadDoorT_task_stat_desc = {
  /* context                  */  ReadDoorT_CONTEXT,
  /* stack                    */  ReadDoorT_STACK,
  /* entry point (function)   */  ReadDoorT_function,
  /* internal ressource       */  NULL,
  /* task id                  */  ReadDoorT_id,
#if WITH_OSAPPLICATION == YES
  /* OS application id        */  
#endif
  /* task base priority       */  2,
  /* max activation count     */  1,
  /* task type                */  TASK_EXTENDED,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES

  /* execution budget */        0,
  /* timeframe        */        0, 
  /* pointer to the timing
     protection descriptor    */ NULL

#endif
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
/*
 * Dynamic descriptor of task ReadDoorT
 */
VAR(tpl_proc, OS_VAR) ReadDoorT_task_desc = {
  /* resources                      */  NULL,
#if WITH_OSAPPLICATION == YES
  /* if > 0 the process is trusted  */  0,    
#endif /* WITH_OSAPPLICATION */
  /* activate count                 */  0,
  /* task priority                  */  2,
  /* task state                     */  AUTOSTART
};

/*
 * Event structure of task ReadDoorT
 */
VAR(tpl_task_events, OS_VAR) ReadDoorT_task_evts = {
  /* event set  */ 0,
  /* event wait */ 0
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_CODE
#include "tpl_memmap.h"

FUNC(void, OS_CODE) SysTick_Handler(void)
{
  /* ISR1s */

  /* ISR2s */
  /* COUNTERs */
  tpl_tick_SysTick();
  /* ACK */

}

#define OS_STOP_SEC_CODE
#include "tpl_memmap.h"

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"
/*=============================================================================
 * Definition and initialization of process tables (tasks and isrs)
 */
CONSTP2CONST(tpl_proc_static, AUTOMATIC, OS_APPL_DATA)
tpl_stat_proc_table[TASK_COUNT+ISR_COUNT+1] = {
  &DoorLockIndicationTask_task_stat_desc,
  &LEDSwitchTask_task_stat_desc,
  &ReadDoorT_task_stat_desc,
  &IDLE_TASK_task_stat_desc
};

CONSTP2VAR(tpl_proc, AUTOMATIC, OS_APPL_DATA)
tpl_dyn_proc_table[TASK_COUNT+ISR_COUNT+1] = {
  &DoorLockIndicationTask_task_desc,
  &LEDSwitchTask_task_desc,
  &ReadDoorT_task_desc,
  &IDLE_TASK_task_desc
};

CONSTP2VAR(tpl_task_events, AUTOMATIC, OS_APPL_DATA)
tpl_task_events_table[EXTENDED_TASK_COUNT] = {
  &DoorLockIndicationTask_task_evts,
  &LEDSwitchTask_task_evts,
  &ReadDoorT_task_evts
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*=============================================================================
 * Definition and initialization of Alarm related structures
 */
/*-----------------------------------------------------------------------------
 * Alarm Time10ms_Alarm descriptor
 *
 * This alarm does a set of event Time_10ms_Event to task ReadDoorT
 */


#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

CONST(tpl_setevent_action, OS_CONST) Time10ms_Alarm_action = {
  {
    /* action function  */    tpl_action_setevent
  },
  /* task id              */  ReadDoorT_id,
  /* event mask           */  Time_10ms_Event_mask
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"
 
#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

CONST(tpl_alarm_static, OS_CONST) Time10ms_Alarm_static = {
  {
    /* pointer to counter           */  &SystemCounter_counter_desc,
    /* pointer to the expiration    */  tpl_raise_alarm
#if (WITH_ID == YES)
    /* id of the alarm for tracing  */  , Time10ms_Alarm_id
#endif
#if WITH_OSAPPLICATION == YES
    /* OS application id            */  , 
#endif
  },
  /* action of the alarm  */  (tpl_action *)&Time10ms_Alarm_action
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

VAR(tpl_time_obj, OS_VAR) Time10ms_Alarm_alarm_desc = {
    /* pointer to the static part   */  (tpl_time_obj_static *)&Time10ms_Alarm_static,
    /* next alarm                   */  NULL,
    /* prev alarm                   */  NULL,
    /* cycle                        */  10,
    /* date                         */  10,
    /* State of the alarm           */  ALARM_AUTOSTART
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"
CONSTP2VAR(tpl_time_obj, AUTOMATIC, OS_APPL_DATA)
  tpl_alarm_table[ALARM_COUNT] = {
  &Time10ms_Alarm_alarm_desc
};
#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

/*=============================================================================
 * Declaration of flags functions
 */
/* $FLAGSFUNCTIONS$ */

/*=============================================================================
 * Definition and initialization of Ready List structures
 */
#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

VAR(tpl_heap_entry, OS_VAR) tpl_ready_list[5];
VAR(tpl_rank_count, OS_VAR) tpl_tail_for_prio[4] = {
  0,
  0,
  0
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

/**
 * @internal
 *
 * tpl_kern gather informations on the current executing object and
 * the previous one
 */
VAR(tpl_kern_state, OS_VAR) tpl_kern =
{
  NULL,                      /* no running task static descriptor   */
  &IDLE_TASK_task_stat_desc, /* elected task to run is idle task    */
  NULL,                      /* no running task dynamic descriptor  */
  &IDLE_TASK_task_desc,      /* elected task to run is idle task    */
  INVALID_PROC_ID,           /* no running task so no ID            */
  INVALID_PROC_ID,           /* idle task has no ID                 */
  NO_NEED_SWITCH,            /* no context switch needed at start   */
  FALSE,                     /* no schedule needed at start         */
#if WITH_MEMORY_PROTECTION == YES
  1,                         /* at early system startup, we run in  */
                             /*  kernel mode, so in trusted mode    */
#endif /* WITH_MEMORY_PROTECTION */
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#define API_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"
CONSTP2CONST(char, AUTOMATIC, OS_APPL_DATA) proc_name_table[TASK_COUNT + ISR_COUNT + 1] = {

  "DoorLockIndicationTask",
  "LEDSwitchTask",
  "ReadDoorT",
  "*idle*"
};
#define API_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/* End of file tpl_app_config.c */
