/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Door_Lock_Indication_SWC_Type.h
 * Generated on: Sat Aug 10 11:52:25 EET
 ********************************************************************/

#ifndef RTE_DOOR_LOCK_INDICATION_SWC_TYPE_H
#define RTE_DOOR_LOCK_INDICATION_SWC_TYPE_H


#include "Rte_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/*************************** range types *****************************/

#define uint8_LowerLimit  (0U)
#define uint8_UpperLimit (255U)

/************************ enumeration types **************************/



#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_DOOR_LOCK_INDICATION_SWC_TYPE_H */
