/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorIndication_ECU_Abstraction_SWC_.c
 * Generated on: Sat Aug 10 11:52:25 EET
 ********************************************************************/

#include "string.h"
#include "Rte_DoorIndication_ECU_Abstraction_SWC.h"


extern Rte_DE_uint8 Read_Door_State_Runnable_DoorState_PPort_Door_State;


const Rte_CDS_DoorIndication_ECU_Abstraction_SWC Rte_Instance_DoorIndication_ECU_Abstraction_SWC = {
&Read_Door_State_Runnable_DoorState_PPort_Door_State
};

const Rte_CDS_DoorIndication_ECU_Abstraction_SWC * const Rte_Inst_DoorIndication_ECU_Abstraction_SWC = &Rte_Instance_DoorIndication_ECU_Abstraction_SWC;




void Rte_IWrite_DoorIndication_ECU_Abstraction_SWC_Read_Door_State_Runnable_DoorState_PPort_Door_State (uint8 Door_State)
{
	(Rte_Inst_DoorIndication_ECU_Abstraction_SWC)->Read_Door_State_Runnable_DoorState_PPort_Door_State->value = Door_State;
}
uint8* Rte_IWriteRef_DoorIndication_ECU_Abstraction_SWC_Read_Door_State_Runnable_DoorState_PPort_Door_State(void)
{
	return &(Rte_Inst_DoorIndication_ECU_Abstraction_SWC)->Read_Door_State_Runnable_DoorState_PPort_Door_State->value;
}
