/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Door_Lock_Indication_SWC.h
 * Generated on: Sat Aug 10 11:52:25 EET
 ********************************************************************/

#ifndef RTE_DOOR_LOCK_INDICATION_SWC_H
#define RTE_DOOR_LOCK_INDICATION_SWC_H

#include "Rte_Door_Lock_Indication_SWC_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_Door_Lock_Indication_SWC * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_Door_Lock_Indication_SWC * const Rte_Inst_Door_Lock_Indication_SWC;

/************************ application errors *************************/

#define RTE_E_CSIF_LEDSwitch_E_OK ((Std_ReturnType)0)
#define RTE_E_CSIF_LEDSwitch_E_NOT_OK ((Std_ReturnType)1)

/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		InputState_RPort
 * Interface:	SRIF_Door_State
 * DataElement:	Door_State
 * Runnable:	Door_Lock_indication_Runnable
 *****************************************************/
extern uint8 Rte_IRead_Door_Lock_Indication_SWC_Door_Lock_indication_Runnable_InputState_RPort_Door_State (void);
#ifndef IN_RTE_C
#define Rte_IRead_Door_Lock_indication_Runnable_InputState_RPort_Door_State() \
	Rte_IRead_Door_Lock_Indication_SWC_Door_Lock_indication_Runnable_InputState_RPort_Door_State()
#endif

/*****************************************************
 * Port: 		LEDSwitchClient_RPort
 * Interface:	CSIF_LEDSwitch
 * Operation:	LED_Switch
 * Sync/Async:	Synchronous
 *****************************************************/
extern Std_ReturnType Rte_Call_Door_Lock_Indication_SWC_LEDSwitchClient_RPort_LED_Switch (uint8 LED_State);
#ifndef IN_RTE_C
#define Rte_Call_LEDSwitchClient_RPort_LED_Switch(LED_State) \
	Rte_Call_Door_Lock_Indication_SWC_LEDSwitchClient_RPort_LED_Switch(LED_State)
#endif


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	Door_Lock_indication_Runnable
 * DataElement: Door_State
 *****************************************************/
extern void Door_Lock_indication(void);


/******** ARUnit-specific function pointers for server call delegates *********/
typedef Std_ReturnType (*FunctionPtr_Door_Lock_Indication_SWC_LEDSwitchClient_RPort_LED_Switch)(uint8 LED_State);


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_DOOR_LOCK_INDICATION_SWC_H */
