/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorIndication_ECU_Abstraction_SWC.h
 * Generated on: Sat Aug 10 11:52:25 EET
 ********************************************************************/

#ifndef RTE_DOORINDICATION_ECU_ABSTRACTION_SWC_H
#define RTE_DOORINDICATION_ECU_ABSTRACTION_SWC_H

#include "Rte_DoorIndication_ECU_Abstraction_SWC_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_DoorIndication_ECU_Abstraction_SWC * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_DoorIndication_ECU_Abstraction_SWC * const Rte_Inst_DoorIndication_ECU_Abstraction_SWC;

/************************ application errors *************************/

#define RTE_E_CSIF_LEDSwitch_E_OK ((Std_ReturnType)0)
#define RTE_E_CSIF_LEDSwitch_E_NOT_OK ((Std_ReturnType)1)

/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		DoorState_PPort
 * Interface:	SRIF_Door_State
 * DataElement:	Door_State
 * Runnable:	Read_Door_State_Runnable
 *****************************************************/
extern void Rte_IWrite_DoorIndication_ECU_Abstraction_SWC_Read_Door_State_Runnable_DoorState_PPort_Door_State (uint8 Door_State);
#ifndef IN_RTE_C
#define Rte_IWrite_Read_Door_State_Runnable_DoorState_PPort_Door_State(RTEData) \
	Rte_IWrite_DoorIndication_ECU_Abstraction_SWC_Read_Door_State_Runnable_DoorState_PPort_Door_State(RTEData)
#endif
extern uint8* Rte_IWriteRef_DoorIndication_ECU_Abstraction_SWC_Read_Door_State_Runnable_DoorState_PPort_Door_State(void);
#ifndef IN_RTE_C
#define Rte_IWriteRef_Read_Door_State_Runnable_DoorState_PPort_Door_State() \
	Rte_IWriteRef_DoorIndication_ECU_Abstraction_SWC_Read_Door_State_Runnable_DoorState_PPort_Door_State()
#endif

/*****************************************************
 * Port: 		LEDSwitch_PPort
 * Interface:	CSIF_LEDSwitch
 * Operation:	LED_Switch
 *****************************************************/
extern Std_ReturnType LED_Switch(uint8 LED_State) ;


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	Read_Door_State_Runnable
 * Period:		0.01
 *****************************************************/
extern void Read_Door_State(void);


/******** ARUnit-specific function pointers for server call delegates *********/


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_DOORINDICATION_ECU_ABSTRACTION_SWC_H */
